# -*- js -*-
{
    "image": "debian/stable",
    "packages": ["git", "make", "netcat-openbsd", "build-essential",
                 "luajit", "lua5.1", "lua5.2", "lua5.3", "lua5.4"],
    "sources": ["https://git.sr.ht/~technomancy/fennel"],
    "tasks": [{"build":"IRC_CHANNEL=\"#fennel\" make -C fennel ci"}],
}
