#!/usr/bin/env lua

package.path = arg[0]:match("(.-)[^\\/]+$") .. "?.lua;" .. package.path
local fennel = require('fennel')

if arg[1] == "--repl" then
    print("Welcome to fennel!")
    fennel.repl()
elseif arg[1] == "--compile" then
    local f = assert(io.open(arg[2], "rb"))
    print(fennel.compile(f:read("*all")))
    f:close()
elseif #arg == 1 then
    local f = assert(io.open(arg[1], "rb"))
    fennel.eval(f:read("*all"))
    f:close()
else
    print [[
Usage: fennel --options scripts

  --repl    :  Launch a repl
  --compile :  Compile a file and write the Lua to stdout]]
end
